In [59]:
import numpy 
import random
import numpy as np
mylist = [1,2,3,4,5,6,7,8,9,10,11,12]
a = np.reshape(mylist,(4,3))
b = np.reshape(mylist,(2,3,2))

print(a)
print(b)

print("This is a random number between the given numbers : " + str(random.randint(3, 9)))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
This is a random number between the given numbers : 5


In [60]:
import pandas as pd

In [63]:
new = pd.Series([1,5,2,7,4,3,3])
print(new)

0    1
1    5
2    2
3    7
4    4
5    3
6    3
dtype: int64


In [9]:
# now this data can be saved to a csv file in a better formatted manner.

In [65]:
print(new.index)

RangeIndex(start=0, stop=7, step=1)


In [66]:
print(new.values)

[1 5 2 7 4 3 3]


In [67]:
print(new.keys)

<bound method Series.keys of 0    1
1    5
2    2
3    7
4    4
5    3
6    3
dtype: int64>


In [70]:
import numpy as np
new2 = np.array([6,4,2,5,4,7,8])
print(new2)

[6 4 2 5 4 7 8]


In [74]:
print(type(new.values), type(new2))

<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [78]:
fruits = ["Apple" , "Strawberry" , "banana" , "pineapple"]
Quantities = [20,21,45,12]

pd.Series(Quantities , index = fruits)

Apple         20
Strawberry    21
banana        45
pineapple     12
dtype: int64

In [89]:
fruits = ["Apple" , "Strawberry" , "banana" , "pineapple"]
fruit1 = ["Apple" , "pomegrenate" , "grape" , "mushroom"]
new3 = pd.Series([14,15,17,20],index=fruits)
new4 = pd.Series([20,21,45,12],index=fruit1)
print(new3)

Apple         14
Strawberry    15
banana        17
pineapple     20
dtype: int64


In [90]:
print(new3 + new4)

Apple          34.0
Strawberry      NaN
banana          NaN
grape           NaN
mushroom        NaN
pineapple       NaN
pomegrenate     NaN
dtype: float64


In [94]:
print(new3['Apple'])

14


In [ ]:
import matplotlib.pyplot as plt